language: java
jdk:
- oraclejdk8


services:
  - docker
  
before_install:
- mvn clean package
- docker build -t babadgunia/sms-back .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
